config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    get :followings, on: :member
    get :followers, on: :member
  resource :relationships, only: [:create, :destroy]
  end
  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end


  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image, destroy: false

  has_many :relationships, foreign_key: "user_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def self.search(search,word)
    if search == "perfect_match"
                     @user = User.where(name: "#{word}")
    elsif search == "forward_match"
                     @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
                     @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
                     @user = User.where("name LIKE?","%#{word}%")
    else
                     @user = User.all
    end
  end

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    #@user = User.find(params[:user_id])
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.all
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.all
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>

        <% unless current_user == user %>
        <td>
          <% if current_user.following?(user) %>
           <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
           <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        </td>
        <% end %>

        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, followings_user_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, followers_user_path(user.id) %></th>
  </tr>
</table>

<% if user.id == current_user.id %>
<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>
<% end %>

<% unless current_user == user %>
<div class='row'>
 <% if current_user.following?(user) %>
  <%= link_to("フォロー外す", user_relationships_path(user.id), { method: :delete, class: "btn btn-success"}) %>
 <% else %>
  <%= link_to("フォローする", user_relationships_path(user.id), { method: :post, class: "btn btn-success"}) %>
 <% end %>
</div>
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
      <h2>Follower Users</h2>
      <% if @users.count > 0 %>
      <table class='table'>
       <thead>
         <tr>
           <th>image</th>
           <th>name</th>
           <th colspan="3"></th>
         </tr>
       </thead>
       <tbody>
         <% @users.each do |user| %>
           <tr>
             <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
             <td><%= user.name %></td>
             <td>フォロー数:<%= user.followings.count %></td>
             <td>フォロワー数:<%= user.followers.count %></td>
             <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
           </tr>
         <% end %>
       </tbody>
      </table>
      <% else %>
       <p>ユーザーはいません</p>
      <% end %>

app/views/users/followings.html.erb
      <h2>Follow Users</h2>
      <% if @users.count > 0 %>
      <table class='table'>
       <thead>
         <tr>
           <th>image</th>
           <th>name</th>
           <th colspan="3"></th>
         </tr>
       </thead>
       <tbody>
         <% @users.each do |user| %>
           <tr>
             <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
             <td><%= user.name %></td>
             <td>フォロー数:<%= user.followings.count %></td>
             <td>フォロワー数:<%= user.followers.count %></td>
             <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
           </tr>
         <% end %>
       </tbody>
      </table>
      <% else %>
       <p>ユーザーはいません</p>
      <% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>

      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
       <thead>
        <tr>
         <th></th>
         <th>Title</th>
         <th>Opinion</th>
         <th colspan="3"></th>
        </tr>
       </thead>
       <tbody>
        <% @books.each do |book| %>
        <tr>
         <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
         </td>
         <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
         <td><%= book.body %></td>
         <td>コメント数:<%= book.book_comments.count %></td>
        </tr>
        <% end %>
       </tbody>
      </table>
    </div>
  </div>
</div>